# Generated by Django 4.2 on 2024-10-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_has_sizes'),
        ('profiles', '0002_rename_default_user_userprofile_user'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to='profiles.userprofile'),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
    ]
