# Generated by Django 4.2 on 2024-10-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
