# Generated by Django 4.2 on 2024-10-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newslettersubscriber_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
