# Generated by Django 4.2 on 2024-10-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newslettersubscriber_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'verbose_name_plural': 'Newsletter subscribers'},
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='confirmed',
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(error_messages={'unique: This email is already subscribed'}, max_length=255, unique=True),
        ),
    ]
