# Generated by Django 3.2.25 on 2024-09-21 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='colorway',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='sneaker',
            name='size_range',
        ),
        migrations.AddField(
            model_name='sneaker',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
