# Generated by Django 3.2.25 on 2024-09-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
