# Generated by Django 3.2.25 on 2024-09-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
