# Generated by Django 4.2 on 2024-10-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
    ]
